version: '3'
services:
  layersdb:
    image: mariadb:10.2
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
     - MYSQL_DATABASE=layersdb
     - MYSQL_ROOT_PASSWORD=testingpw
    container_name: layersdb
  layersapp:
    depends_on:
      - layersdb
    build: .
    image: halstead/layerindex-app
    hostname: localhost
    volumes:
     - layersmeta:/opt/workdir
    environment:
     #- SECRET_KEY=<set this here>
     - DATABASE_PASSWORD=testingpw
     - DATABASE_HOST=layersdb
     #- EMAIL_HOST=<set this here>
     #- DEBUG=1
    container_name: layersapp
  layersweb:
    depends_on:
      - layersapp
    build:
      context: .
      dockerfile: Dockerfile.web
    image: halstead/layerindex-web
    hostname: localhost
    ports:
     - "8080:80"
    ## For production you want these instead
    # - "80:80"
    # - "443:443"
    volumes:
     - layersstatic:/usr/share/nginx/html
    # - layerscerts:/etc/letsencrypt
    container_name: layersweb
  layersrabbit:
    image: rabbitmq:alpine
    container_name: layersrabbit
  layerscelery:
    depends_on:
      - layersdb
      - layersapp
      - layersrabbit
    image: halstead/layerindex-app
    volumes:
     - layersmeta:/opt/workdir
    environment:
     #- SECRET_KEY=<set this here>
     - DATABASE_PASSWORD=testingpw
     - DATABASE_HOST=layersdb
     #- EMAIL_HOST=<set this here>
     #- DEBUG=1
    container_name: layerscelery
    command: /usr/local/bin/celery -A layerindex.tasks worker --loglevel=info --workdir=/opt/layerindex

volumes:
  layersmeta:
  layersstatic:
  layerscerts:
