# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0025_update_retcode'),
        ('layerindex', '0014_wrtemplates'),
    ]

    operations = [
    ]
