# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0044_extendedprovides'),
        ('layerindex', '0026_merge_20181002_1725'),
    ]

    operations = [
    ]
